name: Deploy simple web DEF

on:
  push:
    branches: ["main"]

# Permisos necesarios para que GitHub pueda publicar
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # 1. Bajamos el código
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Configuramos Pages
      - name: Setup Pages
        uses: actions/configure-pages@v4

      # 3. ESTE ES EL PASO QUE FALTABA O FALLABA: Empaquetar la web
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # El punto significa "carpeta actual" (la raíz)
          path: '.'

      # 4. Publicamos el paquete
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
